namespace:
  name: demo
replicaCount: 2
image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent
resources:
  requests:
    CPU: 70m
    memory: 256Mi
service:
  type: ClusterIP
  port: 80
configmap:
  data: "version: 1.17.0"


